### ISSUE TITLE
Release 1.0-beta-7

### ISSUE THREAD

**Issue by agudian** [mojohaus/webstart#1] opened 2015-06-04 08:25 UTC
Hi there,

any chance we can get a release of 1.0-beta-7? I'm running into problems with the -SNAPSHOT version references that seems to have been fixed a year ago.

Let me know if I can help with the release! :smiley: 

Thanks,
Andreas

cc @tchemit  / @khmarbaise

**Comment by batmat** [comment] 2015-06-04 12:59
Hi Andreas, I think this should be feasible very soon, but we're at least
still stuck while Sonatype & Ben work out how to reenable access to
nexus.codehaus.org (auth broken currently).

2015-06-04 10:25 GMT+02:00 Andreas Gudian notifications@github.com:

> Hi there,
> 
> any chance we can get a release of 1.0-beta-7? I'm running into problems
> with the -SNAPSHOT version references that seems to have been fixed a year
> ago.
> 
> Let me know if I can help with the release! [image: :smiley:]
> 
> Thanks,
> Andreas
> 
> cc @tchemit https://github.com/tchemit / @khmarbaise
> https://github.com/khmarbaise
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mojohaus/webstart/issues/1.

## 

Baptiste <Batmat> MATHUS - http://batmat.net
Sauvez un arbre,
Mangez un castor !

**Comment by tchemit** [comment] 2015-06-05 14:32
@Batmat  Let me know when you think it will be ok for release time, I can then manage it.

**Comment by batmat** [comment] 2015-06-05 14:58
See last mail from Brian on the mojohaus ml. We could ask for an ETA but
currently we don't have one.

**Comment by giovanitadei** [comment] 2015-08-20 19:18
Hi,

Any news on this release? It seems I can´t compile my project with Java 8 without a fix that´s already been implemented and should be released with version 1.0-beta-7, so any idea on when this might happen would really useful.

Thanks,

Giovani

**Comment by tchemit** [comment] 2015-08-28 07:11
Hi @giovanitadei, @agudian  I will try to do a new release next week, just have to check what's going on at the MojoHaus, I was away for a long time now. Sorry for the delay.

**Comment by giovanitadei** [comment] 2015-09-09 18:05
Appreciate it! I´ll be on the lookout for updates. Cheers.

**Comment by hazriqpedia** [comment] 2015-09-28 12:40
I cant compile this with Java 8 even it is in the profile.

**Comment by solomax** [comment] 2015-09-28 12:41
I can compile using java8, what is the error? are you using 1.0.7-SNAPSHOT? maybe maven caching isue?

**Comment by hazriqpedia** [comment] 2015-09-29 03:30
@solomax whoops. My bad. Managed to compiled the project successfuly but stuck with this:

`[DEBUG] Configuring mojo org.codehaus.mojo.webstart:webstart-maven-plugin:1.0-beta-7:jnlp-inline from plugin realm ClassRealm[plugin>org.codehaus.mojo.webstart:webstart-maven-plugin:1.0-beta-7
, parent: sun.misc.Launcher$AppClassLoader@70dea4e]
Sep 29, 2015 3:03:07 AM org.sonatype.guice.bean.reflect.Logs$JULSink warn
WARNING: Error injecting: org.codehaus.mojo.webstart.sign.DefaultSignTool
java.lang.NoClassDefFoundError: org/apache/maven/shared/utils/cli/javatool/JavaToolException`

**Comment by solomax** [comment] 2015-09-29 05:20
What is your maven version? I'm using latest: 3.3.3

**Comment by hazriqpedia** [comment] 2015-09-29 06:12
@solomax mine one is Apache Maven 3.0.4 (r1232337; 2012-01-17 08:44:56+0000)

**Comment by solomax** [comment] 2015-09-29 06:37
maybe you can update to the recent version?

**Comment by dizzzz** [comment] 2015-10-01 12:13
any idea when a new version is released with the Java8 change in it? release on github would probably help ppl already :-)

**Comment by dizzzz** [comment] 2015-10-07 11:05
I filed PR  #11 for a specific issue we have regarding HTTP proxies ; We'd appreciate if you can pull it in before releasing the new version. @tdecsi

**Comment by giovanitadei** [comment] 2015-10-26 16:25
Any news on this release. My team´s getting ready to migrate to Java 8, so the issue is becoming more urgent for us. Any forecast you could give me would really help! Cheers.

**Comment by misiekzap** [comment] 2015-10-30 13:27
I would be also very thankful if new release would be ready. We also want to move to Java 8. Thanks!

**Comment by skybutter** [comment] 2015-11-09 19:31
I got the same Keytool exception with Java 8, but was able to use the webstart plugin by adding the following to the pom.xml:

<pre>
<code>
   &lt;build&gt;
      &lt;pluginManagement>
         &lt;plugins>
            
            &lt;plugin>
                &lt;groupId>org.codehaus.mojo&lt;/groupId>
                &lt;artifactId>webstart-maven-plugin&lt;/artifactId>
                &lt;version>1.0-beta-6&lt;/version>
                &lt;dependencies>
                    &lt;dependency>
                        &lt;groupId>org.codehaus.mojo&lt;/groupId>
                        &lt;artifactId>webstart-pack200-impl&lt;/artifactId>
                        &lt;version>1.0-beta-6&lt;/version>
                    &lt;/dependency>
                    &lt;dependency>
                        &lt;groupId>org.codehaus.mojo&lt;/groupId>
                        &lt;artifactId>keytool-api-1.7&lt;/artifactId>
                        &lt;version>1.4&lt;/version>
                    &lt;/dependency>
                &lt;/dependencies>
            &lt;/plugin>
            
...
</code>
</pre>

**Comment by giovanitadei** [comment] 2015-11-11 21:06
I´m afraid it didn´t work for me. Got the following error:

[ERROR] Failed to execute goal org.codehaus.mojo:webstart-maven-plugin:1.0-beta-6:jnlp-inline (default) on project monitor: Unable to parse configuration of mojo org.codehaus.mojo:webstart-maven-plugin:1.0-beta-6:jnlp-inline for parameter pack200: Cannot find default setter in class org.codehaus.mojo.webstart.Pack200Config

**Comment by giovanitadei** [comment] 2015-11-11 21:19
Ooops, never mind. That problem was due to a documented change when upgrading from version 1.0-beta-3:

http://www.mojohaus.org/webstart/webstart-maven-plugin/upgrade.html

Seems to be working. Thanks, skybutter!

**Comment by misiekzap** [comment] 2015-12-04 12:05
Thanks for response, but although all suggested changes I still have exception and can't find any information in google. Maybe you know solution? Thanks in advance.

[ERROR] Failed to execute goal org.codehaus.mojo:webstart-maven-plugin:1.0-beta-6:jnlp-download-servlet (default) on project project1: Execution default of goal org.codehaus.mojo:we
bstart-maven-plugin:1.0-beta-6:jnlp-download-servlet failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:webstart-maven-plugin:1.0-beta-6:jnlp-download-servlet (default) on project project1
: Execution default of goal org.codehaus.mojo:webstart-maven-plugin:1.0-beta-6:jnlp-download-servlet failed.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal org.codehaus.mojo:webstart-maven-plugin:1.0-beta-6:jnlp-download-servlet failed.
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
Caused by: java.lang.NullPointerException
        at java.net.URI$Parser.parse(URI.java:3042)
        at java.net.URI.<init>(URI.java:588)
        at java.net.URI.create(URI.java:850)
        at org.codehaus.mojo.webstart.sign.DefaultSignTool.getKeyStoreFile(DefaultSignTool.java:244)
        at org.codehaus.mojo.webstart.sign.SignConfig.init(SignConfig.java:177)
        at org.codehaus.mojo.webstart.AbstractBaseJnlpMojo.signOrRenameJars(AbstractBaseJnlpMojo.java:673)
        at org.codehaus.mojo.webstart.JnlpDownloadServletMojo.execute(JnlpDownloadServletMojo.java:194)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        ... 21 more

**Comment by ankon** [comment] 2016-02-16 12:15
Anything blocking the release? That is, apart from the pending PRs, which seem to be all quite useful to be included in such a release...

**Comment by pranahata** [comment] 2016-02-25 14:56
For those in need, we have a fork of this java webstart maven plugin here: https://bitbucket.org/anahata/anahata-webstart/commits/all

Works with the latest java 8 and has parallel packing, unpacking and signing, additional manifest cleanup,  support to define an application preloader and basic support for native libs

**Comment by solomax** [comment] 2016-02-25 15:04
@pranahata do you have any plans to release it? and make available via maven?

**Comment by pranahata** [comment] 2016-02-26 04:27
@solomax artifacts are in our public maven repo if you need them. I updated the wiki with instructions https://bitbucket.org/anahata/anahata-webstart/wiki/Home

**Comment by tchemit** [comment] 2016-02-26 06:36
Hi huys, thansk for your effort, do you think it would be possible de merge your work in this repository ? If you give me the PR I will merge them.

**Comment by pranahata** [comment] 2016-02-26 07:39
@tchemit  Hey Tony, yes, more than happy for you to pull / merge any of our changes. But what does PR mean?

**Comment by tchemit** [comment] 2016-02-26 08:19
Pull Request :)

**Comment by tchemit** [comment] 2016-02-26 08:20
or Merge Request as you prefer.

**Comment by pranahata** [comment] 2016-02-26 08:23
@tchemit  Tony, the project is in bitbucket and I am not sure how we can merge as I don't think there is any git upstream project configured in our repo. If you know how to do it, we can give it a go.

**Comment by tchemit** [comment] 2016-02-26 08:29
@pranahata  Do you need to keep this repository? Hope the question is not offending ? Maybe you could join MojoHaus organization, in that way we could work on the same git ?

**Comment by dizzzz** [comment] 2016-02-26 08:33
@tchemit there are a few more interesting PRs waiting, including one from me :-) Would you consider pulling them in? What to do to have these pulled in?

**Comment by tchemit** [comment] 2016-02-26 09:11
@dizzzz Yes sir! I'am back on the project ;)

**Comment by pranahata** [comment] 2016-02-26 09:22
@tchemit Yes, we need and want to keep our own repository. Thanks for the invitation but we are happy with how we have it today.

**Comment by dizzzz** [comment] 2016-02-26 09:59
@pranahata since @tchemit is 'back', this archive is/should be leading in what is released to the community (via the maven repos). Having your work in this archive would probably make maintenance a bit more easy for you.

**Comment by pranahata** [comment] 2016-02-26 11:13
@dizzzz It's all right mate, we are happy with our repo

**Comment by tchemit** [comment] 2016-02-26 15:25
@pranahata I don't understand why you have change all the package names in your fork. I really can't get your code in a easy way.

Could you manage something for us - the https://bitbucket.org/anahata/anahata-webstart/commits/d5b6ba7a9fe28a23c8fb9f2092cb953048adef6d .
I will cut a release 1.0-beta-7, hope we can add this in a future (but soon!) 1.0-beta-8

**Comment by pranahata** [comment] 2016-02-27 00:48
@tchemit no, I don't want to

**Comment by tchemit** [comment] 2016-02-27 06:58
@pranahata I don't understand your reply, you don't want to what ? to contribute back ? If so not very nice of you :( Anyway I have clone your fork, and will do my job, with or without you!

**Comment by tchemit** [comment] 2016-02-27 08:10
Ok this is time to release 1.0-beta-7 (at last!), I am closing this issue. Stay tuned

**Closed as completed by tchemit** 2016-02-27 08:10 UTC
Labels: question

**Comment by solomax** [comment] 2016-03-04 13:08
Hello, @tchemit what repository are you using for releases?
it seems to be impossible to find both 1.0-beta-7-SNAPSHOT and 1.0-beta-7
it is absent 
here http://repository.jboss.org/org/codehaus/mojo/webstart-maven-plugin/1.0-beta-7-SNAPSHOT/
and here: http://repo1.maven.org/maven2/org/codehaus/mojo/webstart-maven-plugin/

**Comment by tchemit** [comment] 2016-03-04 15:06
I have just close the sonatype release repository, the artifact should be soon or later in Maven Central.

I did not still announce it : everything must be synch before this. Ok ?

**Comment by solomax** [comment] 2016-03-04 15:14
OK, will wait for it
Thanks!

**Comment by tchemit** [comment] 2016-03-04 15:48
@solomax  Go-go-go!

**Comment by solomax** [comment] 2016-03-04 15:51
Thanks for the update!

**Comment by Schalli1987** [comment] 2016-03-15 12:55
Is there any changelog available or a new site report with the changes between beta-6 and beta-7?
http://www.mojohaus.org/webstart/webstart-maven-plugin/ seems not to be up to date any more...

**Comment by tchemit** [comment] 2016-03-15 13:09
@Schalli1987 t need to rebuild the maven site, actually it is dead (don't ask me why?).

You can see what has been done here https://github.com/mojohaus/webstart/issues?q=milestone%3A1.0-beta-7
